# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  ImageName: 'ditiacr001.azurecr.io/von-image:$(version)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Build an image'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'ditiacr001'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        addBaseImageData: false
  
    - task: Docker@2
      displayName: 'Push the Docker Image to ACR'
      inputs:
        containerRegistry: 'ACRConnection_DITI'
        repository: 'ditiacr001'
        command: 'push'
        tags: ''